### ISSUE TITLE
Remove ERT WG from spec-dashboard

### ISSUE THREAD

**Issue by brewerj** [w3c/spec-dashboard#3]
Philippe, hadn't we already closed that, with info provided from Shadi, and your meeting with W3M? Any pending actions to address? - Judy

**Comment by tripu** [comment]
(pinging @plehegar)

**Comment by dontcallmedom** [comment]
fwiw, ERT will disappear from the dashboard once the group is officially closed; since I don't think there is value in tracking ERT closure here, I'm closing the issue.
